apiVersion: v1
kind: Service
metadata:
  name: {{NODE_NAME}}
spec:
  clusterIP: None
  selector:
    app: {{NODE_NAME}}
  ports:
  - name: http
    port: 9200
    targetPort: 9200
  - name: transport
    port: 9300
    targetPort: 9300